name: Sync lnproxy relays

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 12 * * 0" # Run every Sunday at noon

jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch and process JSON
        run: |
          curl https://raw.githubusercontent.com/lnproxy/lnproxy-webui2/main/assets/relays.json -o lnproxy_tmplist.json
          node .github/workflows/scripts/lnproxy-sync.js

      - name: Commit and push if it's not up to date
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./frontend/static/lnproxies.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update LNProxy relay list"
          git push

      - name: Remove tmp lnproxy json file
        run: rm lnproxy_tmplist.json
