name: Sync lnproxy relays

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 12 * * 0" # Run every Sunday at noon

jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Fetch and process lnproxy relay JSON file
        run: |
          curl https://raw.githubusercontent.com/lnproxy/lnproxy-webui2/main/assets/relays.json -o lnproxy_tmplist.json
          node ./scripts/lnproxy-sync.js
          git add ./frontend/static/lnproxies.json

      - name: Remove tmp lnproxy json file
        run: rm lnproxy_tmplist.json

      - name: Get the date for use in subsequent steps
        id: getdate
        run: echo "current_date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Submit pull request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Update LNProxy relay list on ${{ env.current_date }}"
          committer: GitHub Action <action@github.com>
          branch: "lnproxy-${{ env.current_date }}"
          delete-branch: true
          title: "[GitHub Action] Update LNProxy relay list ${{ env.current_date }}"
